Use MemCacheStore instead of Dalli
Dalli store is not supported in Rails 6.1 and causes this error:
```
NoMethodError
undefined method `dup_value!' for #<String:0x00007f9cf66fb130>
```

The fix is to swap out for MemCacheStore, as we've done here:
https://github.com/alphagov/collections/commit/d8a6a51378e8bc37122a558e895ab7610916f179